#spring:
#  config:
#    activate:
#      on-profile: dev

spring:
  profiles:
    active: dev
server:
  servlet:
    context-path: /api

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://124.221.96.103:9000
  bucketName: test
