server:
  port: 8088
spring:
  datasource:
    druid:
      url: jdbc:mysql://124.221.96.103:3306/warehouse?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: tzt1234560.0
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-wait: 3000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
  redis:
    host: 124.221.96.103
    port: 6379
    password: tzt123456
    database: 3
    timeout: 5000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
