#spring:
#  config:
#    activate:
#      on-profile: dev

spring:
  profiles:
    active: dev
  application:
    name: warehouse
server:
  servlet:
    context-path: /api

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://47.96.109.221:9000
  bucketName: warehouse

#logging:
#  file:
#    name: ${spring.application.name}.log
#    path: ./logs
#  level:
#    root: info
